import '../styles/globals.css'
import Navbar from '@/components/nav'
import Footer from '@/components/footer'

export const metadata = {
  title: 'Next Portfolio Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <main>
        {children}
      </main>
      <Footer />
    </html>
  )
}
